apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260603-190212-tbn9wmjrbugv-service
spec:
  selector:
    app: enterprise-system-20260603-190212-tbn9wmjrbugv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
